= Guidelines

:sectnums:

:DataConductor: link:apidocs/guru/mikelue/jdut/DataConductor.html[DataConductor]
:DataRow: link:apidocs/guru/mikelue/jdut/datagrain/DataRow.html[DataRow]
:DataGrain: link:apidocs/guru/mikelue/jdut/datagrain/DataGrain.html[DataGrain]
:DefaultOperatorFactory: link:apidocs/guru/mikelue/jdut/operation/DefaultOperatorFactory.html[DefaultOperatorFactory]
:ConductorConfig: link:apidocs/guru/mikelue/jdut/ConductorConfig.html[ConductorConfig]
:DuetConductor: link:apidocs/guru/mikelue/jdut/DuetConductor.html[DuetConductor]
:JdbcFunction: link:apidocs/guru/mikelue/jdut/jdbc/JdbcFunction.html[JdbcFunction]
:DataGrainDecorator: link:apidocs/guru/mikelue/jdut/decorate/DataGrainDecorator.html[DataGrainDecorator]
:YamlConductorFactory: link:apidocs/guru/mikelue/jdut/yaml/YamlConductorFactory.html[YamlConductorFactory]
:ConductorContext: link:apidocs/guru/mikelue/jdut/ConductorContext.html[ConductorContext]
:ThreadLocal: https://docs.oracle.com/javase/8/docs/api/java/lang/ThreadLocal.html[ThreadLocal]
:IInvokedMethodYamlFactoryListener: link:apidocs/guru/mikelue/jdut/testng/IInvokedMethodYamlFactoryListener.html[IInvokedMethodYamlFactoryListener]
:ISuiteYamlFactoryListener: link:apidocs/guru/mikelue/jdut/testng/ISuiteYamlFactoryListener.html[ISuiteYamlFactoryListener]
:ITestContextYamlFactoryListener: link:apidocs/guru/mikelue/jdut/testng/ITestContextYamlFactoryListener.html[ITestContextYamlFactoryListener]
:JdutYamlFactory: link:apidocs/guru/mikelue/jdut/junit4/JdutYamlFactory.html[JdutYamlFactory]
:OperatorPredicate: link:apidocs/guru/mikelue/jdut/function/OperatorPredicate.html[OperatorPredicate]
:DefaultOperators: link:apidocs/guru/mikelue/jdut/operation/DefaultOperators.html[DefaultOperators]
:postgresql: https://www.postgresql.org/[PostgreSql]
:mysql: https://www.mysql.com/[MySql]
:oracle: https://www.oracle.com/database/index.html[Oracle]
:mssql: https://www.microsoft.com/en-cy/sql-server/sql-server-downloads[MsSql]
:h2: https://www.h2database.com/[H2]
:hsqldb: https://hsqldb.org/[HsqlDb]
:derby: https://db.apache.org/derby/[Derby]
:DataGrainOperator: link:apidocs/guru/mikelue/jdut/operation/DataGrainOperator.html[DataGrainOperator]
:Consumer: https://docs.oracle.com/javase/8/docs/api/java/util/function/Consumer.html[Consumer]
:DataSource: https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html[DataSource]
:Connection: https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html[Connection]
:Reader: https://docs.oracle.com/javase/8/docs/api/java/io/Reader.html[Reader]
:Map: https://docs.oracle.com/javase/8/docs/api/java/util/Map.html[Map]
:JUnit4: https://junit.org/junit4/[JUnit4]
:TestNG: https://testng.org/[TestNG]

This article contains the main building blocks for usage of JDUT.

For quick example, see link:examples.html[Examples].

'''

== Java API

This section describes the usage of pure-Java API for building/cleaning data

=== Set-up data grain

{DataGrain}:: Used to set-up values and definitions of data
https://docs.oracle.com/javase/8/docs/api/java/util/function/Supplier.html[Supplier<?>]:: The value of field could be a supplier, which working as lazy-evaluation

See link:xref-test/guru/mikelue/jdut/datagrain/DataGrainTest.html[DataGrainTest] for full example

Quick example:

[source,java]
----
import idv.mikelue.jdut.datagrain.DataGrain;

DataGrain dataGrainByDefine = DataGrain.build(
	/**
	 * Defines the table meta-data
	 * The columns would be indexed by sequence of builds
	 */
	tableSchemaBuilder -> {
		tableSchemaBuilder
			.name("tab_1") // Mandatory
			.keys("col_1", "col_2"); // Used by DELETE operation
	},
	// :~)
	/**
	 * Adds the data of table
	 */
	rowsBuilder -> {
		rowsBuilder.implicitColumns(
			"col_1", "col_2", "col_3", "col_4"
		)
		/**
		 * Implicit data
		 */
		.addValues(10, "CC-1", () -> "AC-2", null)
		.addValues(11, "CC-1", () -> "AC-2", null)
		// :~)
		/**
		 * Explicit data
		 */
		.addFields(
			rowsBuilder.newField("col_1", 12),
			rowsBuilder.newField("col_2", 13),
			rowsBuilder.newField("col_3", () -> "AN-78")
			rowsBuilder.newField("col_4", () -> "AN-78")
		);
		// :~)
	}
	// :~)
);
----

=== Execute operator with data grain

{DataConductor}:: The conductor depending on {DataSource}

{DataGrainOperator}:: The code(SQL) executes on database with {DataGrain}

{DefaultOperatorFactory}:: The factory for fetching operator(may be link:apidocs/guru/mikelue/jdut/vendor/package-summary.html[vendor-specific]) by name.

[source,java]
----
import guru.mikelue.jdut.DataConductor;
import guru.mikelue.jdut.operation.DefaultOperators;

/**
 * dataSource - The initialized data source
 *
 * This conductor would load schema of database to complement the complete information of column.
 */
DataConductor dataConductor = DataConductor.build(dataSource);

/**
 * Executes the "INSERT"(defined in OperatorFactory) with data grain
 */
dataConductor.conduct(dataGrainByDefine, operatorFactory.get(DefaultOperators.INSERT));
----

=== Aggregation of data grains

link:apidocs/guru/mikelue/jdut/datagrain/DataGrain.html#aggregate-guru.mikelue.jdut.datagrain.DataGrain-[DataGrain.aggregate] - Used to aggregate multiple data grains in sequence

See detail sample of link:xref-test/guru/mikelue/jdut/datagrain/DataGrainTest.html[DataGrainTest.aggregate]

[source,java]
----
import guru.mikelue.jdut.datagrain.DataGrain;

// dg_1 - The object of DataGrain
// dg_2 - Another object of DataGrain

// The data of dg_1 with data of dg_2....
DataGrain aggregatedDataGrains = dg_1.aggregate(dg_2);
----

=== Data grain decoration

A decorator is a lambda to modify a {DataRow}, which is the internal data of a {DataGrain}.

==== Decorate data grain(decorator)
You could implement functional interface of link:apidocs/guru/mikelue/jdut/decorate/DataGrainDecorator.html[DataGrainDecorator] to decorate an instance of {DataGrain}.

[source,java]
----
import guru.mikelue.jdut.datagrain.DataGrain;
import guru.mikelue.jdut.decorate.DataGrainDecorator;

DataGrainDecorator dataGrainDecorate = rowBuilder -> rowBuilder
	.field("col_1", Types.INTEGER, 55)
	.field("col_2", rowBuilder<Integer>.getData("col_1").orElse(0) + 1)
	.field("col_3", () -> "EXP-01");

DataGrain decoratedDataGrain = dataGrain.decorate(dataGrainDecorate);
----

==== Chaining of decorator
You could use method of link:apidocs/guru/mikelue/jdut/decorate/DataGrainDecorator.html#chain-guru.mikelue.jdut.decorate.DataGrainDecorator-[DataGrainDecoration.chain()] to chain multiple decorations.

[source,java]
----
import guru.mikelue.jdut.decorate.DataGrainDecorator;

DataGrainDecorator dataGrainDecorate_1 = (rowBuilder) -> {
	/* Your decoration...*/
}
DataGrainDecorator dataGrainDecorate_2 = (rowBuilder) -> {
	/* Your decoration...*/
}

DataGrainDecoration chainedDecorate = dataGrainDecorate_1.chain(dataGrainDecorate_2);
----

=== Data operator

You may use {DataGrainOperator} to implement your own operations to database.

link:apidocs/guru/mikelue/jdut/operation/DataRowsOperator.html[DataRowsOperator]:: Accepts a list of {DataRow}s

link:apidocs/guru/mikelue/jdut/operation/DataRowOperator.html[DataRowOperator]:: Accepts a {DataRow}

==== Composition of operations
You could composite operations for interception of data operation.

A link:apidocs/guru/mikelue/jdut/operation/DataGrainOperator.SurroundOperator.html[SurroundOperator] is a lambda to surround a {DataGrainOperator}. The returned object is another {DataGrainOperator} with same signature.

[source,java]
----
import guru.mikelue.jdut.operation.DefaultOperators;
import guru.mikelue.jdut.operation.DataGrainOperator;

DataGrainOperator specialInsert = DefaultOperators.INSERT.surroundedBy(
	surroundedOp -> (conn, dataGrain) -> {
		/* Your surrounding before the calling of surrounded operation */

		surroundedOp.operate(conn, dataGrain)

		/* Your surrounding after the calling of surrounded operation */
	};
)
----

==== Operate data in transaction
See link:apidocs/guru/mikelue/jdut/function/DatabaseTransactional.html[DatabaseTransactional] and
link:apidocs/guru/mikelue/jdut/function/DatabaseSurroundOperators.html[DatabaseSurroundOperators]

[source,java]
----
/**
 * By DataSourceConsumer
 */
import guru.mikelue.jdut.function.DatabaseTransactional;
import guru.mikelue.jdut.operation.DefaultOperators;

dataConductor.conduct(
	DefaultOperators.INSERT.surroundedBy(
		DatabaseTransactional::simple
	)
);
----

=== Data types

==== For Java API

The build-in operators of JDUT would use the type of value
to decide which method of `setXXX` in https://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html[PreparedStatement]
to be called for setting parameter of SQL.

https://docs.oracle.com/javase/8/docs/api/java/util/Date.html[java.util.Date]:: the engine would use https://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html#setTimestamp-int-java.sql.Timestamp-[PreparedStatement.setTimestamp()].

**Type cannot be decided**:: the engine would use https://docs.oracle.com/javase/8/docs/api/java/sql/PreparedStatement.html#setObject-int-java.lang.Object-[PreparedStatement.setObject()]

==== For YAML
. The engine(loading YAML) builds the data into {DataGrain}. +
	Hence the target type is the decided by the conversion of YAML engine.
. You may assign desired type of data by YAML tagging

[source,yaml]
----

%TAG !jdut! tag:jdut.mikelue.guru:1.0/
%TAG !dbtype! tag:jdut.mikelue.guru:jdbcType:1.8/
%TAG !sql! tag:jdut.mikelue.guru:sql:1.0/

'''
- !sql!table tab_1 [
  # With column name
  {
	  col_1: !dbtype!smallint 10, col_2: "String Value",
	  col_3: !dbtype!timestamp "2010-05-05 10:20:35+08"
  },
  # Other rows...
]
----

==== Scalar Value
[cols=">,>,^.^",width=50%]
|===
^| YAML Type : JDBC type  ^| Accept type of JDBC ^| Misc

| `!!binary` : `VARBINARY`
| BINARY, BLOB, LONGVARBINARY, VARBINARY
| <<misc-1>> as base64

| `!!bool` : `BOOLEAN`
| BIT, BOOLEAN, +
TINYINT, SMALLINT, INTEGER, BIGINT, +
DECIMAL, NUMERIC, REAL, +
DOUBLE, FLOAT
| If the target type of JDBC is *numeric*: `True(1)`, `False(0)`

| `!!float` : `DOUBLE`
| DECIMAL, DOUBLE, FLOAT, REAL, NUMERIC
| <<misc-1>>

| `!!int` : `INTEGER`
| TINYINT, SMALLINT, INTEGER, BIGINT, +
 NUMERIC, DECIMAL, REAL, +
 DOUBLE, FLOAT
| <<misc-1>>

| `!!str` : `VARCHAR`
| CHAR, VARCHAR, LONGVARCHAR, +
 NCHAR, NVARCHAR, LONGNVARCHAR, +
 CLOB, NCLOB
|

| `!!timestamp` : `TIMESTAMP`
| DATE, TIME, TIMESTAMP
| <<misc-1>>

| `!!null` : `null value`
| doesn't matter
|
|===

[[misc-1,**1*]]**1* - Could be converted to text-type of SQL

`NUMERIC` and `DECIMAL`:: the value would be converted into https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html[BigDecimal].

==== Complex Value
For type of complex value, you could use https://docs.oracle.com/javase/8/docs/api/java/util/function/Supplier.html[Supplier<?>] to create data of these types:
**ARRAY**, **DISTINCT**, **JAVA_OBJECT**, **OTHER**, **REF**, **REF_CURSOR**, **ROWID**, **STRUCT**

==== References
* https://bitbucket.org/asomov/snakeyaml/wiki/Documentation#markdown-header-yaml-tags-and-java-types[Data types provided by SnakeYaml]
* https://bitbucket.org/asomov/snakeyaml/wiki/Documentation[SnakeYaml Documentation]

'''

== YAML API

The configuration of YAML condcutor:

{ConductorConfig}::
	Bean as facade of configuration for conducting data. +
	The practices of the config are defined by implementation of engine. +
	The link:apidocs/guru/mikelue/jdut/yaml/YamlConductorFactory.html#build-javax.sql.DataSource-java.util.function.Consumer-[YamlConductorFactory.build()]
	or link:apidocs/guru/mikelue/jdut/yaml/YamlConductorFactory.html#conductResource-java.lang.String-java.util.function.Consumer-[YamlConductorFactory.conductResource()]
	method let you set-up the instance of {ConductorConfig}.

link:apidocs/guru/mikelue/jdut/ConductorConfig.Builder.html[ConductorConfig.Builder]:: The fed object of {Consumer} to set-up an instance of {ConductorConfig}

=== Set-up YamlConductorFactory

{YamlConductorFactory}::
	The most important service to build an instance of {DuetConductor}. +
	This factory depends on {DataSource} given to link:apidocs/guru/mikelue/jdut/yaml/YamlConductorFactory.html#build-javax.sql.DataSource-[build()] method. +
	You can define {ConductorConfig} to customize {DataGrainDecorator} or {JdbcFunction}, etc,.

{DefaultOperatorFactory}::
	The default factory used by {YamlConductorFactory}. +
	You may customize the factory by using link:apidocs/guru/mikelue/jdut/ConductorConfig.Builder.html#operatorFactory-guru.mikelue.jdut.operation.OperatorFactory-[ConductorConfig.Builder.operatorFactory()] to set the instance.


[source,java]
----
// dataSource - The initialized data source

YamlConductorFactory yamlConductor = YamlConductorFactory.build(
	dataSource,
	builder -> builder
		// The factory of operator
		.operatorFactory(defaultOperationFactory)
		// The optional file loader for convertion string of file name to InputStream or Reader
		.resourceLoader((fileName) -> new FileReader(fileName))
		.namedOperator(
			"INSERT_AND_CHECK",
			(connection, dataRows) -> { /* Your database operations */ }
		)
		.namedDecorator(
			"[V1]",
			(dataRowBuilder) -> { /* Your data decoration */ }
		)
		.namedJdbcFunction(
			"func_1",
			connection -> { /* Your code of JDBC */ }
		)
);
----

=== Build DuetConductor

{DuetConductor}:: This interface defines build/clean data for https://en.wikipedia.org/wiki/Unit_testing[unit test].

[source,java]
----
import guru.mikelue.jdut.DuetConductor;

DuetConductor testConductor_1 = yamlFactory.conductNamedResource(
	"org/your/package/CarDaoTest-addNew.yaml",
	/**
	 * You could overrides configuration of YamlConductorFactory
	 */
	configure -> configure
		.namedDecorator("add_value", your_decorator)
	// :~)
);

// Consturct a content of YAML with Yaml.DEFAULT_TAGS directly(instead of file)
DuetConductor testConductor_2 = yamlConductor.conduct(
   YamlTags.DEFAULT_TAGS +
   "---\n" +
   "- !sql!table tab_1: {" +
   "  col_1: 40, col_2: \"VGA-1\"" +
   "}"
);
----

'''

==== Resource loading

While using link:apidocs/guru/mikelue/jdut/yaml/YamlConductorFactory.html#conductResource-java.lang.String-java.util.function.Consumer-[YamlConductorFactory.conductResource(String, Consuemr<ConductorConfig.Builder>)] to load YAML file,+
you could configure how to convert a String to a {Reader} by link:apidocs/guru/mikelue/jdut/ConductorConfig.Builder.html#resourceLoader-java.util.function.Function-[ConductorConfig.Builder.resourceLoader()].

See link:apidocs/guru/mikelue/jdut/yaml/ReaderFunctions.html[ReaderFunctions] for build-in functions.

'''

==== Execute build/clean
The {DuetConductor} should be used in proper event defined by https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#Java[testing framework].

For {JUnit4}::
	* link:apidocs/guru/mikelue/jdut/DuetConductor.html#build--[build()] - Could be used in https://junit.org/junit4/javadoc/latest/org/junit/Before.html[@Before] annotated method.
	* link:apidocs/guru/mikelue/jdut/DuetConductor.html#clean--[clean()] - Could be used in https://junit.org/junit4/javadoc/latest/org/junit/After.html[@After] annotated method.

For {TestNG}::
	* link:apidocs/guru/mikelue/jdut/DuetConductor.html#build--[build()] - Could be used in https://jitpack.io/com/github/cbeust/testng/master/javadoc/org/testng/annotations/BeforeMethod.html[@BeforeMethod] annotated method.
	* link:apidocs/guru/mikelue/jdut/DuetConductor.html#clean--[clean()] - Could be used in https://jitpack.io/com/github/cbeust/testng/master/javadoc/org/testng/annotations/AfterMethod.html[@AfterMethod] annotated method.

Following example to execute the two methods when testing:

[source,java]
----
testConductor_1.build();
testConductor_2.build();

try {
	/* Your testing code */
} finally {
	testConductor_2.clean();
	testConductor_1.clean();
}
----

=== YAML Syntax

See link:yaml-syntax.html[YAML Syntax]

'''

== Operators/Decorators

=== Build-in operators

The {DefaultOperators} constructs operator-inspection of vendor-specific, uses it would be a good idea.

* INSERT
** As `DefaultOperators::insert`
** Use of SQL `INSERT <table_name>`, directly.
* UPDATE
** As `DefaultOperators::update`
** Use of SQL `UPDATE <table_name> SET <col_1> = <v_1>, ... WHERE <conditions>`, directly
* REFRESH
** As `DefaultOperators::refresh`
** Gets the data, if the data is existing, then updates the data
** Otherwise, inserts the data
* DELETE
** As `DefaultOperators::delete`
** Use of SQL `DELETE FROM <table_name> WHERE <conditions>`, directly.
* DELETE_ALL
** As `DefaultOperators::deleteAll`
** Use of SQL `DELETE FROM <table_name>`, directly.
* TRUNCATE
** As `DefaultOperators::truncate`
** Use of SQL `TRUNCATE TABLE <table_name>`, directly.
* NONE
** As `DefaultOperators::none`
** This operation has no effect to database.

[source,java]
----

import guru.mikelue.jdut.operation.DefaultOperatorFactory;
import guru.mikelue.jdut.operation.DefaultOperators;

DefaultOperatorFactory factory = DefaultDataOperatorFactory.build(
	dataSource, builder -> {}
);

dataConductor.conduct(
	factory.get(DefaultOperators.INSERT),
	dataGrain
);
----

=== Build-in decorators

==== Value replacement

[source,java]
----

import guru.mikelue.jdut.decorate.ReplaceFieldDataDecorator;
import guru.mikelue.jdut.decorate.DataGrainDecorator;

/**
 * The decorate to replace string by assigned value
 */
DataGrainDecorator replaceDecorate = ReplaceFieldDataDecorator.build(
	builder -> builder
		.replaceWith(30, 90); // Replacement by object
		.replaceWith("[V1]", () -> 10); // Replacement by supplier
		.replaceWith(dataField -> dataField.getColumnName().equals("col_9"), "Another Value"); // Replacement by predict of datafield
);
----

===== Default value
You can replace value with null-value checking

* **DataFieldPredicates.nullValue(tableName, columnName)** - Builds a predicate to check null value for a column on table
* **DataFieldPredicates::nonSupplier** - A predicate to check if the data of field doesn't comes from https://docs.oracle.com/javase/8/docs/api/java/util/function/Supplier.html[Supplier]
  * This is used if you don't want to load data before the processing of operator

[source,java]
----
// builder - builder of ReplaceFieldDataDecorator.build()

builder -> builder
	.replaceWith(DataFieldPredicates.nullValue("tab_1", "col_1"), "DEFAULT-VALUE")
----

'''

==== Not defined column
You may use link:apidocs/guru/mikelue/jdut/function/DataRowBuilderPredicates.html#notExistingColumn-java.lang.String-java.lang.String-[DataRowBuilderPredicates::notExistingColumn] to predicate
a decorator {a row}[DataRow] with not-defined column.

[source,java]
----

import guru.mikelue.jdut.function.DataRowBuilderPredicates;
import guru.mikelue.jdut.decorate.DataGrainDecorator;

DataGrainDecorator decorator = (rowBuilder -> rowBuilder.field("col_1", -1))
	.predicate(DataRowBuilderPredicates.notExistingColumn("tabl_1", "col_1"));
----

See https://docs.oracle.com/javase/8/docs/api/java/util/function/Predicate.html[Predicate.and(), .or()]

=== Conductor Context

While the {DataConductor} is executing, you may access its current working object of {Connection} provided from {ConductorContext}, which keeps the connection in {ThreadLocal}.

A good example to use conductor context is **value function**, you may access current session of database while generating data of a field.

Lazy loading of value function::
	Since conductor context is available only when it is executing, +
	you should keep in mind that {DataGrainDecorator} shouldn't access link:apidocs/guru/mikelue/jdut/datagrain/DataRow.Builder.html#getData-java.lang.String-[DataRow.Builder.getData(`<field_name>`)] to trigger the value function. +
	Instead, using link:apidocs/guru/mikelue/jdut/datagrain/DataRow.Builder.html#getDataSupplier-java.lang.String-[DataRow.Builder.getDataSupplier(`<field_name>`)].isPresent() to check whether or not the value comes from a value function.

[red]*You must not close the object of {Connection} from the context*.

[source,java]
----

Connection conn = ConductorContext.getCurrentConnection()
	.orElseThrow(() -> new Exception("NoContext"));

/* 1) Use of connection */
/* 2) Do not close it!! */
----

==== Threading

Any execution of link:apidocs/guru/mikelue/jdut/DataConductor.html#conduct-guru.mikelue.jdut.datagrain.DataGrain-guru.mikelue.jdut.operation.DataGrainOperator-[DataConductor.conduct(...)] would initialize a new object of {Connection}, which is put into {ConductorContext}.

'''

== Database Vendor

=== Vendor-specific operators

{DefaultOperatorFactory} would try to fetch best-implementation for vendor-specific operations.

You can override the operators implemented by JDUT.

The method of link:apidocs/guru/mikelue/jdut/operation/DefaultOperatorFactory.Builder.html[DefaultOperatorFactory.Builder.add] accepts two arguments:

{OperatorPredicate}::
	The method of link:apidocs/guru/mikelue/jdut/function/OperatorPredicate.html#testMetaData-java.sql.DatabaseMetaData-[testMetaData(DatabaseMetaData)] is used to
	check the meta data of current connection to database. +
	This predicate returning **true value** means to use your mapping of operators.

{Map}<String, DataGrainOperator>:: The mapping is used to fetch operator by name for the fisrt matched {OperatorPredicate}.

You don't have to define all of the names defined in {DefaultOperators} in the {Map} of operators.
{DefaultOperatorFactory} would fetch a default one if your mapping doesn't contain the name.

See https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html[DatabaseMetaData].


**The first matched predicte would be selected for the vendor-specific operation**

[source,java]
----
import guru.mikelue.jdut.operation.DefaultOperatorFactory;
import guru.mikelue.jdut.operation.OperatorFactory;

// dataSource - The initialized data source
// yourMapOfOperators - Your customized mapping of operators
OperatorFactory yourFactory = DefaultOperatorFactory.build(
	dataSource,
	builder -> builder
		.add(
			metaData -> metaData.getDriverName().contains("something"),
			yourMapOfOperators
		)
);

----

=== Notes

Following list states the databases and JDBC drivers which have been tested:

[cols="<,>,>,<",width=50%]
|===
^| Database Vendor ^| Database Version ^| JDBC Version ^| Misc

| {postgresql}
| 9.4
| jdbc41
|

| {mysql}
| 5.6
| 5.1
|

| {oracle}
| 11g express
| 11.2.0(thin)
|

| {mssql}
| 2013 express
| 4.2
|

| {h2}
| 1.4
| 1.4
|

| {hsqldb}
| 2.3
| 2.3
|

| {derby}
| 10.11
| 10.11
|
|===

==== Keys of row
In order to execute `DELETE` or `UPDATE` more precisely, following priority for looking up one or multiple columns in a table is applied to build `WHERE` statement:

. Setting of keys in link:apidocs/guru/mikelue/jdut/datagrain/SchemaTable.Builder.html#keys-java.lang.String...-[SchemaTable.Builder.keys(String...)] or `keys` of YAML
. *primary key*
. *unique index* with least number of columns and all of their value have non-null value
	* Choose first constraint(as order of https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getIndexInfo-java.lang.String-java.lang.String-java.lang.String-boolean-boolean-[DatabaseMetaData.getIndexInfo(...)])
